Module 1 Portfolio desktop version
the-catalystmc/microverse-portfolio-setup pull request #4
Opened 2021-06-10 21:39 UTC by the-catalystmc

In this project the following was done:

- Parse a design from FIgma for the desktop version of Portfolio.
- Use media queries to make sure that the website displays correctly on desktop screens.
- Add a fixed Navbar
- Make sure that there are no linter errors.

2021-06-10 22:40 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @the-catalystmc, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
- No Linters errors ✔️ 
- Good desktop view ✔️ 

## Aspects to improve ♻️

- [ ] Maybe the style for diff sizes in responsible could improve, look how appears your page on diff sizes (I recommend you use Chrome dev tools to check the diff sizes for your page)

| Desktop | Ipad |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/20563252/121605195-951ea380-ca11-11eb-9270-4cc5a90df6f1.png) | ![image](https://user-images.githubusercontent.com/20563252/121605292-c6976f00-ca11-11eb-896a-b7cd446bd49a.png) |

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, consider:
- [OPTIONAL] Use more details on form in every sizes
![image](https://user-images.githubusercontent.com/20563252/121605542-3574c800-ca12-11eb-83d5-0a0441630ac8.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-10 22:40 UTC, vichuge commented on style.css
> +@media (min-width: 992px) {
- [ ] Please, use media queries for the Desktop breakpoint in the CSS file.(min-width > 992px - 1100px), for example: `@media screen and (min-width: 992px) {` 🐶

2021-06-11 00:40 UTC, Davidosky007 requested changes
Hi @the-catalystmc, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-06-11 00:40 UTC, Davidosky007 commented on style.css
> +@media screen and (min-width: 992px) {
I suggest you increase the min-width as the previous reviewer asked to eg (min-width: 993 - upward) min-width should be greater than 992px to 1100px as this is the required media query for desktop applications

2021-06-11 01:13 UTC, Davidosky007 commented on style.css
> +@media screen and (min-width: 992px) {
nice job 👍

2021-06-11 01:14 UTC, Davidosky007 commented
Hi @the-catalystmc,
![CR GIF](https://user-images.githubusercontent.com/52497246/121616404-c2437400-ca5a-11eb-91ab-2655717de79b.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-11 01:18 UTC, merged